// Barrel: re-exports the machinery the resource accessors are built from (ADR-0097 / ADR-0101).

export * from "./data-resource";
export * from "./data-reader";
export type * from "./read-record";
export * from "./data-writer";
export type * from "./write-record";
export * from "./descriptor";
export * from "./build-write-url";
export * from "./first-write-result-id";
export type * from "./resource-page";
export * from "./run-read";
export * from "./page-url";
export * from "./page-reader";
export * from "./catalog";
export * from "./raw-value";
export type * from "./deps";
export * from "./decoder";
export * from "./paging";
export * from "./append-paging";
export * from "./paginate";
export * from "./field-param";
export * from "./field-param-setter";
export * from "./query";
export * from "./append-read-query";
export * from "./build-read-params";
export * from "./expand";
export * from "./selected-expansions";
export * from "./apply-expand";
export * from "./expansion-catalogs";
export * from "./guard-raw-expansion";
export * from "./image";
export * from "./apply-image";
export * from "./guard-image-write";
export * from "./write-many";
export * from "./read-many";
export * from "./master-resource";
export * from "./master-reader";
