import { describe, expect, it } from "vitest";

import type { Field } from "../resources/field";
import { CUSTOM_DATA_TYPES } from "./custom-data-types";
import { generateFieldDecls } from "./generate-field-decls";
import { fieldTypeValueOf } from "../porters/field-type";
import type { FieldCatalogSource } from "./read-custom-catalog";

const sourceOf = (
  byResource: Readonly<Record<string, readonly Partial<Field>[]>>,
): FieldCatalogSource & { readonly queries: unknown[] } => {
  const queries: unknown[] = [];
  return {
    queries,
    field: {
      of: (resource) => ({
        searchAll: (query) => {
          queries.push({ resource, query });
          const rows = byResource[resource] ?? [];
          let i = 0;
          return {
            [Symbol.asyncIterator]: () => ({
              next: () =>
                Promise.resolve(
                  i < rows.length
                    ? { done: false as const, value: rows[i++] }
                    : { done: true as const, value: undefined },
                ),
            }),
          };
        },
      }),
    },
  };
};

describe("generateFieldDecls", () => {
  it("prints a defineFields call for the tenant's fields", async () => {
    const source = sourceOf({
      candidate: [
        { P_Alias: "Person.U_score", P_Type: 3 },
        { P_Alias: "Person.U_source", P_Type: 7 },
      ],
    });

    const src = await generateFieldDecls(source, ["candidate"]);

    expect(src).toBe(
      [
        "// Generated by generateFieldDecls (@joymerrevent/porters-connect).",
        "// Re-run it when the tenant's fields change, and check the result with verifyFields.",
        'import { defineFields } from "@joymerrevent/porters-connect";',
        "",
        "export const myFields = defineFields({",
        "  candidate: (f) => ({",
        "    U_score: f.number(),",
        "    U_source: f.option(),",
        "  }),",
        "});",
        "",
      ].join("\n"),
    );
  });

  it("keeps a deterministic order so regenerating does not reshuffle a committed file", async () => {
    const source = sourceOf({
      job: [
        { P_Alias: "Job.U_zebra", P_Type: 1 },
        { P_Alias: "Job.U_alpha", P_Type: 1 },
        { P_Alias: "Job.U_middle", P_Type: 1 },
      ],
    });

    const src = await generateFieldDecls(source, ["job"]);

    expect(src.indexOf("U_alpha")).toBeLessThan(src.indexOf("U_middle"));
    expect(src.indexOf("U_middle")).toBeLessThan(src.indexOf("U_zebra"));
  });

  it("emits the parameterless form when a resource has nothing to declare", async () => {
    const source = sourceOf({ job: [] });

    const src = await generateFieldDecls(source, ["job"]);

    // `(f) => ({})` would leave the builder unused and trip a lint rule in the consuming project.
    expect(src).toContain("  job: () => ({}),");
  });

  it("follows the caller's resource order", async () => {
    const source = sourceOf({
      job: [{ P_Alias: "Job.U_a", P_Type: 1 }],
      candidate: [{ P_Alias: "Person.U_b", P_Type: 1 }],
    });

    const src = await generateFieldDecls(source, ["job", "candidate"]);

    expect(src.indexOf("job:")).toBeLessThan(src.indexOf("candidate:"));
  });

  it("reads in-use fields only by default", async () => {
    const source = sourceOf({ job: [] });

    await generateFieldDecls(source, ["job"]);

    // Opposite of verifyFields: a template of fields nobody uses is noise, and there is no
    // "missing" report here to be falsified (ADR-0069, accept 時の決定).
    expect(source.queries).toEqual([{ resource: "job", query: { active: 1 } }]);
  });

  it("passes an explicit active through", async () => {
    const source = sourceOf({ job: [] });

    await generateFieldDecls(source, ["job"], { active: -1 });

    expect(source.queries).toEqual([
      { resource: "job", query: { active: -1 } },
    ]);
  });

  it("reads each resource once, names included", async () => {
    const source = sourceOf({
      job: [{ P_Alias: "Job.U_a", P_Type: 1, P_Name: "案件名" }],
    });

    await generateFieldDecls(source, ["job"], { includeNames: true });

    expect(source.queries).toHaveLength(1);
  });

  describe("the tenant's own wording", () => {
    it("is left out by default", async () => {
      const source = sourceOf({
        job: [{ P_Alias: "Job.U_score", P_Type: 3, P_Name: "適性スコア" }],
      });

      const src = await generateFieldDecls(source, ["job"]);

      expect(src).not.toContain("適性スコア");
      expect(src).toContain("U_score: f.number(),");
    });

    it("is added as a comment when asked", async () => {
      const source = sourceOf({
        job: [{ P_Alias: "Job.U_score", P_Type: 3, P_Name: "適性スコア" }],
      });

      const src = await generateFieldDecls(source, ["job"], {
        includeNames: true,
      });

      expect(src).toContain("U_score: f.number(), // 適性スコア");
    });

    it("omits the comment for a field PORTERS returned no name for", async () => {
      const source = sourceOf({ job: [{ P_Alias: "Job.U_score", P_Type: 3 }] });

      const src = await generateFieldDecls(source, ["job"], {
        includeNames: true,
      });

      expect(src).toContain("U_score: f.number(),\n");
    });
  });

  it("names the exported constant as asked", async () => {
    const source = sourceOf({ job: [] });

    const src = await generateFieldDecls(source, ["job"], {
      constName: "tenantFields",
    });

    expect(src).toContain("export const tenantFields = defineFields({");
  });

  // ADR-0069 論点4: a field the library cannot express must be visible in the output, or the
  // reader concludes the tenant does not have it.
  describe("fields it cannot declare become comments, not omissions", () => {
    it("explains an unpublished Field Type", async () => {
      const source = sourceOf({ job: [{ P_Alias: "Job.U_new", P_Type: 99 }] });

      const src = await generateFieldDecls(source, ["job"]);

      expect(src).toContain(
        "// U_new: Field Type 99 is not in PORTERS' published Field Type list",
      );
    });

    it("explains a type that carries no value (16 Reference)", async () => {
      const source = sourceOf({ job: [{ P_Alias: "Job.U_ref", P_Type: 16 }] });

      const src = await generateFieldDecls(source, ["job"]);

      expect(src).toContain(
        "// U_ref: Reference (Field Type 16) carries no value of its own",
      );
    });

    it("explains a system-managed type (11)", async () => {
      const source = sourceOf({ job: [{ P_Alias: "Job.U_sys", P_Type: 11 }] });

      const src = await generateFieldDecls(source, ["job"]);

      expect(src).toContain(
        "// U_sys: System (Field Type 11) is system-managed",
      );
    });

    // Regenerating has to produce the same text (that is why declarations are sorted), so the
    // comments follow the same rule — otherwise Field Read's order decides the diff.
    it("orders the comments by alias, not by the order Field Read returned them", async () => {
      const source = sourceOf({
        job: [
          { P_Alias: "Job.U_zulu", P_Type: 99 },
          { P_Alias: "Job.U_alpha", P_Type: 16 },
          { P_Alias: "Job.U_mike", P_Type: 11 },
        ],
      });

      const src = await generateFieldDecls(source, ["job"]);
      const commented = [...src.matchAll(/^ {4}\/\/ (U_[A-Za-z0-9_]+):/gm)].map(
        (m) => m[1],
      );

      expect(commented).toEqual(["U_alpha", "U_mike", "U_zulu"]);
    });

    it("still uses the parameterless form when only comments remain", async () => {
      const source = sourceOf({ job: [{ P_Alias: "Job.U_new", P_Type: 99 }] });

      const src = await generateFieldDecls(source, ["job"]);

      expect(src).toContain("  job: () => ({");
    });
  });

  // The generated text has to name a real builder method for every declarable type. A typo would
  // only show up when a user pasted the output into their project, so pin it here.
  describe("the time-of-day note on Field Type 12 (ADR-0086)", () => {
    it("tells the reader a dateTime() may be a clock-time field, since Field Read cannot", async () => {
      const source = sourceOf({
        job: [
          { P_Alias: "Job.U_start", P_Type: 12 },
          { P_Alias: "Job.U_note", P_Type: 1 },
        ],
      });

      const src = await generateFieldDecls(source, ["job"]);

      expect(src).toContain(
        "    U_start: f.dateTime(), // FT-12: a time-of-day field has this same Field Type — if this one holds a clock time, use decodeTimeOfDay / encodeTimeOfDay",
      );
      // Only FT-12 gets it.
      expect(src).toContain("    U_note: f.singlelineText(),\n");
    });

    it("follows the field's name when names are included", async () => {
      const source = sourceOf({
        job: [{ P_Alias: "Job.U_start", P_Type: 12, P_Name: "開始時刻" }],
      });

      const src = await generateFieldDecls(source, ["job"], {
        includeNames: true,
      });

      expect(src).toContain("    U_start: f.dateTime(), // 開始時刻 — FT-12:");
    });
  });

  it("emits a builder call for every declarable Data Type", async () => {
    const rows = CUSTOM_DATA_TYPES.map((dataType, i) => ({
      P_Alias: `Job.U_f${String(i).padStart(2, "0")}`,
      P_Type: fieldTypeValueOf(dataType),
    }));

    const src = await generateFieldDecls(sourceOf({ job: rows }), ["job"]);

    expect(src).toContain("U_f00: f.number(),");
    expect(src).toContain("U_f05: f.url(),"); // not f.uRL()
    expect(src).toContain("U_f07: f.dateTime(), // FT-12:");
    expect(src).toContain("U_f12: f.link(),");
    // Nothing fell through to a comment: every declarable type produced a call.
    expect(src).not.toContain("//  ");
    expect(src.match(/f\.[a-zA-Z]+\(\)/g)).toHaveLength(
      CUSTOM_DATA_TYPES.length,
    );
  });
});

// テナントの入力必須を既定で写す（ADR-0089 案3a）。
describe("generateFieldDecls — required", () => {
  it("prints { required: true } for a field the tenant marks required", async () => {
    const source = sourceOf({
      candidate: [
        { P_Alias: "Person.U_score", P_Type: 3, P_Required: 1 },
        { P_Alias: "Person.U_source", P_Type: 7, P_Required: 0 },
      ],
    });
    const src = await generateFieldDecls(source, ["candidate"]);
    expect(src).toContain("    U_score: f.number({ required: true }),\n");
    expect(src).toContain("    U_source: f.option(),\n");
  });

  it("keeps the note after the call when the field is also required", async () => {
    const source = sourceOf({
      candidate: [{ P_Alias: "Person.U_seen", P_Type: 12, P_Required: 1 }],
    });
    const src = await generateFieldDecls(source, ["candidate"]);
    expect(src).toContain(
      "    U_seen: f.dateTime({ required: true }), // FT-12:",
    );
  });
});
